---

- hosts: all
  become: yes
  become_method: sudo

  vars_files:
     - vars/global_vars.yml

  tasks:

     - name: Update hosts file
       action: template src={{ template_hosts }} dest=/etc/hosts
    
     - name: Set timezone to Asia/Bangkok
       timezone:
          name: Asia/Bangkok

     - name: Create the system splunk account for splunk
       user: name=splunk comment="system account for Splunk" shell=/bin/bash state=present

     - name: Create the .ssh directory
       file: path=/home/splunk/.ssh state=directory mode=0700 owner=splunk group=splunk

     - name: Check service Splunk is exists
       stat: path=/etc/init.d/splunk
       register: boot_splunk

     - name: Start Splunk and accept license
       command: "{{ splunk_installpath }}/splunk/bin/splunk start --answer-yes --no-prompt --accept-license --seed-passwd changeme"
       async: 60
       poll: 5
       become: yes
       become_user: splunk 
       ignore_errors: yes
       register: accepted_splunk

     - name: Enable boot start for Splunk & systemd managed
       command: "{{ splunk_installpath }}/splunk/bin/splunk enable boot-start -systemd-managed 0 -user splunk"
       when: 
          - boot_splunk.stat.exists == false
          - accepted_splunk.finished == 1
       ignore_errors: yes

     - name: Lower the minimal free space required (default 5GB, => 1GB to fit VMs space)
       command: "{{ splunk_installpath }}/splunk/bin/splunk set minfreemb 1000 -auth admin:changeme"
       become: yes
       become_user: splunk
       when: accepted_splunk.finished == 1
       ignore_errors: yes

     - name: Change the admin default password
       command: "{{ splunk_installpath }}/splunk/bin/splunk edit user admin -password '{{admin_passwd}}' -auth admin:changeme"
       become: yes
       become_user: splunk
       ignore_errors: yes

     - name: Check asking for password change
       stat: path="{{ splunk_installpath }}/splunk/etc/.ui_login"
       register: p

     - name: Disable asking for password change at first connection
       file: path="{{ splunk_installpath }}/splunk/etc/.ui_login" state=touch owner=splunk group=splunk mode=0555
       when: not p.stat.exists
